tborzyszkowski/DesignPatterns

02Fabryka/Students/kzielinski/Fabryki4.swift

Dzien dobry,
wrzucam to o co Pan mnie prosil na zajeciach czyli Generyczna Abstrakcyjna Fabryka wraz z dwoma prostymi przykladami. Dokladny opis jest zawarty w komentarzach.

Added Generic Abstract factory

---

03Builder/Students/kzielinski/zad1+.swift
03Builder/Students/kzielinski/zad1.swift
03Builder/Students/kzielinski/zad2.swift

PR contains 
done 2 exercises + 1 bonus example which (set properties similar to builder but it's done with closure)

Added done builder exercises + 1small bonus example

---

01Singleton/Students/mrudnicki/mrudnicki.info
01Singleton/Students/mrudnicki/task1/Singleton1.java
01Singleton/Students/mrudnicki/task1/SingletonCore.java
01Singleton/Students/mrudnicki/task1/SingletonInheretanceTest.java
01Singleton/Students/mrudnicki/task2/Singleton2.java
01Singleton/Students/mrudnicki/task2/SingletonSerializationTest.java
01Singleton/Students/mrudnicki/test.info
01Singleton/Students/mrudnicki/zadanie.info
02Fabryka/Students/mrudnicki/task1/Audi.java
02Fabryka/Students/mrudnicki/task1/BMW.java
02Fabryka/Students/mrudnicki/task1/Car.java
02Fabryka/Students/mrudnicki/task1/CarFactory.java
02Fabryka/Students/mrudnicki/task1/Main.java
02Fabryka/Students/mrudnicki/task2/Demo.java
02Fabryka/Students/mrudnicki/task2/animals/Animal.java
02Fabryka/Students/mrudnicki/task2/animals/Cat.java
02Fabryka/Students/mrudnicki/task2/animals/Dog.java
02Fabryka/Students/mrudnicki/task2/animals/Snake.java
02Fabryka/Students/mrudnicki/task2/animals/Tyrannosaurus.java
02Fabryka/Students/mrudnicki/task2/factories/AbstractFactory.java
02Fabryka/Students/mrudnicki/task2/factories/MammalFactory.java
02Fabryka/Students/mrudnicki/task2/factories/ReptileFactory.java
02Fabryka/Students/mrudnicki/task2/factories/SpeciesFactory.java

factory simple & abstract factory

Mrudnicki factory

---

01Singleton/Students/mrudnicki/mrudnicki.info
01Singleton/Students/mrudnicki/task1/Singleton1.java
01Singleton/Students/mrudnicki/task1/SingletonCore.java
01Singleton/Students/mrudnicki/task1/SingletonInheretanceTest.java
01Singleton/Students/mrudnicki/task2/Singleton2.java
01Singleton/Students/mrudnicki/task2/SingletonSerializationTest.java
01Singleton/Students/mrudnicki/test.info
01Singleton/Students/mrudnicki/zadanie.info
02Fabryka/Students/mrudnicki/task1/Audi.java
02Fabryka/Students/mrudnicki/task1/BMW.java
02Fabryka/Students/mrudnicki/task1/Car.java
02Fabryka/Students/mrudnicki/task1/CarFactory.java
02Fabryka/Students/mrudnicki/task1/Main.java
02Fabryka/Students/mrudnicki/task2/Demo.java
02Fabryka/Students/mrudnicki/task2/animals/Animal.java
02Fabryka/Students/mrudnicki/task2/animals/Cat.java
02Fabryka/Students/mrudnicki/task2/animals/Dog.java
02Fabryka/Students/mrudnicki/task2/animals/Snake.java
02Fabryka/Students/mrudnicki/task2/animals/Tyrannosaurus.java
02Fabryka/Students/mrudnicki/task2/factories/AbstractFactory.java
02Fabryka/Students/mrudnicki/task2/factories/MammalFactory.java
02Fabryka/Students/mrudnicki/task2/factories/ReptileFactory.java
02Fabryka/Students/mrudnicki/task2/factories/SpeciesFactory.java
03Builder/Students/mrudnicki/Ciasto.java
03Builder/Students/mrudnicki/Main.java
03Builder/Students/mrudnicki/Pizza.java
03Builder/Students/mrudnicki/Rozmiar.java

Mrudnicki builder

---

01Singleton/Students/dzduniak/inheritance/CommonInterface.java
01Singleton/Students/dzduniak/inheritance/DynamicProxySingleton.java
01Singleton/Students/dzduniak/inheritance/OtherSingleton.java
01Singleton/Students/dzduniak/inheritance/Singleton.java
01Singleton/Students/dzduniak/inheritance/SingletonInterface.java
01Singleton/Students/dzduniak/inheritance/SingletonInterface2.java
01Singleton/Students/dzduniak/inheritance/Test.java
02Fabryka/Students/dzduniak/fabryka/Car.java
02Fabryka/Students/dzduniak/fabryka/CarFactory.java
02Fabryka/Students/dzduniak/fabryka/Model3.java
02Fabryka/Students/dzduniak/fabryka/ModelS.java
02Fabryka/Students/dzduniak/fabryka/ModelX.java
02Fabryka/Students/dzduniak/fabryka/SimpleTeslaFactory.java
02Fabryka/Students/dzduniak/fabryka/Test.java
02Fabryka/Students/dzduniak/functional/GCDCalculator.java
02Fabryka/Students/dzduniak/functional/Test.java

Singleton i fabryka

---

04Prototype/Students/mrudnicki/ClonerTest.java
04Prototype/Students/mrudnicki/engine/Cloner.java
04Prototype/Students/mrudnicki/sample/Child.java
04Prototype/Students/mrudnicki/sample/Parent.java

deep cloning using serialization example

deep cloning using serialization example

---

01Singleton/Students/kkarkucinski/Singelton/Singleton.java
02Fabryka/Students/kkarkucinski/Factory/FactoryApple.java
02Fabryka/Students/kkarkucinski/Factory/FactorySamsung.java
02Fabryka/Students/kkarkucinski/Factory/IPhone6.java
02Fabryka/Students/kkarkucinski/Factory/IPhone7.java
02Fabryka/Students/kkarkucinski/Factory/Phone.java
02Fabryka/Students/kkarkucinski/Factory/PhoneFactory.java
02Fabryka/Students/kkarkucinski/Factory/SamsungS6.java
02Fabryka/Students/kkarkucinski/Factory/SamsungS7.java
02Fabryka/Students/kkarkucinski/Factory/Test.java
03Builder/Students/kkarkucinski/Builder/Client.java
03Builder/Students/kkarkucinski/Builder/OfficePC.java
03Builder/Students/kkarkucinski/Builder/PCBuilder.java
03Builder/Students/kkarkucinski/Builder/PCDirector.java
03Builder/Students/kkarkucinski/Builder/ServerPC.java
03Builder/Students/kkarkucinski/Builder/components/CPU.java
03Builder/Students/kkarkucinski/Builder/components/MotherBoard.java
03Builder/Students/kkarkucinski/Builder/components/PC.java
03Builder/Students/kkarkucinski/Builder/components/VideoCard.java
07Dekorator/Students/kkarkucinski/Dekorator/Cebula.java
07Dekorator/Students/kkarkucinski/Dekorator/Cheeseburger.java
07Dekorator/Students/kkarkucinski/Dekorator/Dodatki.java
07Dekorator/Students/kkarkucinski/Dekorator/Hotdog.java
07Dekorator/Students/kkarkucinski/Dekorator/Jedzenie.java
07Dekorator/Students/kkarkucinski/Dekorator/Salata.java
07Dekorator/Students/kkarkucinski/Dekorator/Ser.java
07Dekorator/Students/kkarkucinski/Dekorator/Zamowienie.java

Proste implementacje Singleton, Builder, Factory, Dekorator

Singleton, Builder, Factory, Dekorator

---

01Singleton/Students/mmichalski/SingletonInh.py
01Singleton/Students/mmichalski/SingletonThreadSafe.py
02Fabryka/Students/mmichalski/AbstractFactory.py
02Fabryka/Students/mmichalski/FactoryMethod.py
02Fabryka/Students/mmichalski/SimpleFactory.py
03Builder/Students/mmichalski/SimpleBuilder.py
04Prototype/Students/mmichalski/Prototype.py
06Adapter/Students/mmichalski/Adapter.py
07Dekorator/Students/mmichalski/Dekorator.py

mmichalski-wzorce

---

01Singleton/Students/mjakobowski/company/Singleton.java
01Singleton/Students/mjakobowski/company/SingletonSerializableDemo.java

Mjakobowski singleton

---

ProjektyStudentow/2017_Szarafiński_Krzysztof/Bajka.java
ProjektyStudentow/2017_Szarafiński_Krzysztof/BazaPracownikow.java
ProjektyStudentow/2017_Szarafiński_Krzysztof/COOL_RESTAURANT.java
ProjektyStudentow/2017_Szarafiński_Krzysztof/Cukiernia.java
ProjektyStudentow/2017_Szarafiński_Krzysztof/Danie.java
ProjektyStudentow/2017_Szarafiński_Krzysztof/DanieDnia.java
ProjektyStudentow/2017_Szarafiński_Krzysztof/DanieWczorajsze.java
ProjektyStudentow/2017_Szarafiński_Krzysztof/Dekorator.java
ProjektyStudentow/2017_Szarafiński_Krzysztof/Deser.java
ProjektyStudentow/2017_Szarafiński_Krzysztof/Drozdzowka.java
ProjektyStudentow/2017_Szarafiński_Krzysztof/Kadry.java
ProjektyStudentow/2017_Szarafiński_Krzysztof/Kawa.java
ProjektyStudentow/2017_Szarafiński_Krzysztof/KawaCzarna.java
ProjektyStudentow/2017_Szarafiński_Krzysztof/KawaEspresso.java
ProjektyStudentow/2017_Szarafiński_Krzysztof/KawaZCukrem.java
ProjektyStudentow/2017_Szarafiński_Krzysztof/KawaZmlekiem.java
ProjektyStudentow/2017_Szarafiński_Krzysztof/Klient.java
ProjektyStudentow/2017_Szarafiński_Krzysztof/Kuchnia.java
ProjektyStudentow/2017_Szarafiński_Krzysztof/Magazyn.java
ProjektyStudentow/2017_Szarafiński_Krzysztof/Menu.java
ProjektyStudentow/2017_Szarafiński_Krzysztof/Narrator.java
ProjektyStudentow/2017_Szarafiński_Krzysztof/Paczek.java
ProjektyStudentow/2017_Szarafiński_Krzysztof/Projekt.java
ProjektyStudentow/2017_Szarafiński_Krzysztof/Recepcja.java
ProjektyStudentow/2017_Szarafiński_Krzysztof/zestawObiadowy.java

w moim projekcie zastosowałem takie worce jak: FASADA, SINGLETON, SIMPLE FACTORY, FACTORY METHOD, DEKORATOR, BUDOWNICZY.
Program generuje opowiadaną przez "narratora" historię która jest interaktywna z użytkownikiem. Wypisywane są na ekranie informacje co aktualnie się dzieje - dzięki temu wiemy, że dany wzorzec jest stosowany.

projekt zaliczeniowy z przedmiotu WZORCE PROJEKTOWE.

---

.gitattributes
01Singleton/Students/2017/ZukAdam/SingletonInheritance/SingletonInheritance.sln
01Singleton/Students/2017/ZukAdam/SingletonInheritance/SingletonInheritance/App.config
01Singleton/Students/2017/ZukAdam/SingletonInheritance/SingletonInheritance/ColorfulLogger.cs
01Singleton/Students/2017/ZukAdam/SingletonInheritance/SingletonInheritance/Interfaces/ILogger.cs
01Singleton/Students/2017/ZukAdam/SingletonInheritance/SingletonInheritance/Logger.cs
01Singleton/Students/2017/ZukAdam/SingletonInheritance/SingletonInheritance/Program.cs
01Singleton/Students/2017/ZukAdam/SingletonInheritance/SingletonInheritance/Properties/AssemblyInfo.cs
01Singleton/Students/2017/ZukAdam/SingletonInheritance/SingletonInheritance/SingletonInheritance.csproj
01Singleton/Students/2017/ZukAdam/SingletonSerialization/SingletonSerialization.sln
01Singleton/Students/2017/ZukAdam/SingletonSerialization/SingletonSerialization/App.config
01Singleton/Students/2017/ZukAdam/SingletonSerialization/SingletonSerialization/Interfaces/ILogger.cs
01Singleton/Students/2017/ZukAdam/SingletonSerialization/SingletonSerialization/Logger.cs
01Singleton/Students/2017/ZukAdam/SingletonSerialization/SingletonSerialization/Program.cs
01Singleton/Students/2017/ZukAdam/SingletonSerialization/SingletonSerialization/Properties/AssemblyInfo.cs
01Singleton/Students/2017/ZukAdam/SingletonSerialization/SingletonSerialization/SingletonSerialization.csproj

Singleton implementations by Adam Żuk.

Adamzuk singletons

---

01Singleton/Students/2017/ddziag/src/main/FileWriter.scala
01Singleton/Students/2017/ddziag/src/main/JavaLikeThreadsafeSingleton.scala
01Singleton/Students/2017/ddziag/src/main/NotThreadSafeSingleton.scala
01Singleton/Students/2017/ddziag/src/main/ScalaLikeThreadsafeSingleton.scala
01Singleton/Students/2017/ddziag/src/main/SerializationSafeSingleton.scala
01Singleton/Students/2017/ddziag/src/test/JavaLikeThreadsafeSingletonSpec.scala
01Singleton/Students/2017/ddziag/src/test/NotThreadsafeSingletonSpec.scala
01Singleton/Students/2017/ddziag/src/test/ScalaLikeThreadsafeSingletonSpec.scala
01Singleton/Students/2017/ddziag/src/test/ScalaVersusJavaTimeSpec.scala
01Singleton/Students/2017/ddziag/src/test/SerializationSafeSingletonSpec.scala
02Fabryka/Students/2017/ddziag/src/scala/abstractfactory/package.scala
02Fabryka/Students/2017/ddziag/src/scala/fm/enemy/Enemy.scala
02Fabryka/Students/2017/ddziag/src/scala/fm/factory/EnemyFactory.scala
02Fabryka/Students/2017/ddziag/src/scala/registration/package.scala
02Fabryka/Students/2017/ddziag/src/scala/scalafactory/package.scala
02Fabryka/Students/2017/ddziag/src/scala/simple/enemy/Enemy.scala
02Fabryka/Students/2017/ddziag/src/scala/simple/factory/EnemyFactory.scala
02Fabryka/Students/2017/ddziag/src/test/abstractfactory/AbstractFactorySpec.scala
02Fabryka/Students/2017/ddziag/src/test/fm/FactoryMethodSpec.scala
02Fabryka/Students/2017/ddziag/src/test/registration/RegistrationSpec.scala
02Fabryka/Students/2017/ddziag/src/test/scalafactory/ScalafactorySpec.scala
02Fabryka/Students/2017/ddziag/src/test/simple/SimpleFactorySpec.scala

Oddanie farybki oraz singletonu, Dominik Dziąg

Oddanie farybki oraz singletonu

---

01Singleton/Students/2017/HallmanMarcin/singletonPattern/pom.xml
01Singleton/Students/2017/HallmanMarcin/singletonPattern/src/main/java/pl/mhallman/java/singletonPattern/singleton/ThreadSafeSingletone.java
01Singleton/Students/2017/HallmanMarcin/singletonPattern/src/main/resources/log4j.properties
01Singleton/Students/2017/HallmanMarcin/singletonPattern/src/test/java/pl/mhallman/java/singletonPattern/AppTest.java
02Fabryka/Students/2017/HallmanMarcin/factoryPattern/pom.xml
02Fabryka/Students/2017/HallmanMarcin/factoryPattern/src/main/java/pl/mhallman/java/factoryPattern/App.java
02Fabryka/Students/2017/HallmanMarcin/factoryPattern/src/main/java/pl/mhallman/java/factoryPattern/factory/CookieFactory.java
02Fabryka/Students/2017/HallmanMarcin/factoryPattern/src/main/java/pl/mhallman/java/factoryPattern/model/ChocoCookie.java
02Fabryka/Students/2017/HallmanMarcin/factoryPattern/src/main/java/pl/mhallman/java/factoryPattern/model/Cookie.java
02Fabryka/Students/2017/HallmanMarcin/factoryPattern/src/main/java/pl/mhallman/java/factoryPattern/model/CrumbleCookie.java
02Fabryka/Students/2017/HallmanMarcin/factoryPattern/src/main/java/pl/mhallman/java/factoryPattern/model/VeggieCookie.java
02Fabryka/Students/2017/HallmanMarcin/factoryPattern/src/main/java/pl/mhallman/java/factoryPattern/store/CookieStore.java
02Fabryka/Students/2017/HallmanMarcin/factoryPattern/src/main/resources/log4j.properties
02Fabryka/Students/2017/HallmanMarcin/factoryPattern/src/test/java/pl/mhallman/java/factoryPattern/AppTest.java
02Fabryka/Students/2017/HallmanMarcin/factoryRegRefPattern/pom.xml
02Fabryka/Students/2017/HallmanMarcin/factoryRegRefPattern/src/main/java/pl/mhallman/java/factoryRegPattern/App.java
02Fabryka/Students/2017/HallmanMarcin/factoryRegRefPattern/src/main/java/pl/mhallman/java/factoryRegPattern/factory/CookieFactory.java
02Fabryka/Students/2017/HallmanMarcin/factoryRegRefPattern/src/main/java/pl/mhallman/java/factoryRegPattern/model/ChocoCookie.java
02Fabryka/Students/2017/HallmanMarcin/factoryRegRefPattern/src/main/java/pl/mhallman/java/factoryRegPattern/model/Cookie.java
02Fabryka/Students/2017/HallmanMarcin/factoryRegRefPattern/src/main/java/pl/mhallman/java/factoryRegPattern/model/CrumbleCookie.java
02Fabryka/Students/2017/HallmanMarcin/factoryRegRefPattern/src/main/java/pl/mhallman/java/factoryRegPattern/model/VeggieCookie.java
02Fabryka/Students/2017/HallmanMarcin/factoryRegRefPattern/src/main/java/pl/mhallman/java/factoryRegPattern/store/CookieStore.java
02Fabryka/Students/2017/HallmanMarcin/factoryRegRefPattern/src/main/resources/log4j.properties
02Fabryka/Students/2017/HallmanMarcin/factoryRegRefPattern/src/test/java/pl/mhallman/java/factoryRegPattern/AppTest.java

Hi,
This PR contains basic example of Singleton Pattern using double-check and thread safe strategy along with two examples of Factory Patterns( Simple factory and Registration).
Please leave a comment if you have any question.
Thanks in advance,
Marcin Hallman

PR with Singleton and Factory patterns

---

01Singleton/Students/2017/KrygerDamian/src/main/java/pl/devdiary/wzorce/singleton/DefaultSafeSingleton.java
01Singleton/Students/2017/KrygerDamian/src/main/java/pl/devdiary/wzorce/singleton/DoubleCheckedSingleton.java
01Singleton/Students/2017/KrygerDamian/src/main/java/pl/devdiary/wzorce/singleton/ReflexionSafeSingleton.java
01Singleton/Students/2017/KrygerDamian/src/main/java/pl/devdiary/wzorce/singleton/SelfInitializedSingleton.java
01Singleton/Students/2017/KrygerDamian/src/main/java/pl/devdiary/wzorce/singleton/SerializationSafeSingleton.java
01Singleton/Students/2017/KrygerDamian/src/main/java/pl/devdiary/wzorce/singleton/SynchronizedSingleton.java
01Singleton/Students/2017/KrygerDamian/src/test/java/pl/devdiary/wzorce/singleton/test/DefaultSafeSingletonTest.java
01Singleton/Students/2017/KrygerDamian/src/test/java/pl/devdiary/wzorce/singleton/test/DoubleCheckedSingletonTest.java
01Singleton/Students/2017/KrygerDamian/src/test/java/pl/devdiary/wzorce/singleton/test/ReflexionTest.java
01Singleton/Students/2017/KrygerDamian/src/test/java/pl/devdiary/wzorce/singleton/test/SelfInitializedSingletonTest.java
01Singleton/Students/2017/KrygerDamian/src/test/java/pl/devdiary/wzorce/singleton/test/SerializationTest.java
01Singleton/Students/2017/KrygerDamian/src/test/java/pl/devdiary/wzorce/singleton/test/SynchronizedSingletonTest.java

Kryger Damian wzorzec Singleton

---

01Singleton/Students/2017/TyczynskiMichal/singleton.py
02Fabryka/Students/2017/TyczynskiMichal/abstract_factory.py
02Fabryka/Students/2017/TyczynskiMichal/factory_wytwarzanie.py
02Fabryka/Students/2017/TyczynskiMichal/simple_factory.py
03Builder/Students/2017/TyczynskiMichal/builder.py
04Prototype/Students/2017/TyczynskiMichal/prototype.py
06Adapter/Students/2017/TyczynskiMichal/adapter.py

Design patterns

---

03Builder/Students/2017/HallmanMarcin/builderPattern/builderPattern.iml
03Builder/Students/2017/HallmanMarcin/builderPattern/pom.xml
03Builder/Students/2017/HallmanMarcin/builderPattern/src/main/java/pl/mhallman/java/builderPattern/App.java
03Builder/Students/2017/HallmanMarcin/builderPattern/src/main/java/pl/mhallman/java/builderPattern/builder/CheapMealBuilder.java
03Builder/Students/2017/HallmanMarcin/builderPattern/src/main/java/pl/mhallman/java/builderPattern/builder/ExpensiveMealBuilder.java
03Builder/Students/2017/HallmanMarcin/builderPattern/src/main/java/pl/mhallman/java/builderPattern/builder/MealBuilder.java
03Builder/Students/2017/HallmanMarcin/builderPattern/src/main/java/pl/mhallman/java/builderPattern/builder/StandardMealBuilder.java
03Builder/Students/2017/HallmanMarcin/builderPattern/src/main/java/pl/mhallman/java/builderPattern/director/Waiter.java
03Builder/Students/2017/HallmanMarcin/builderPattern/src/main/java/pl/mhallman/java/builderPattern/model/Meal.java
03Builder/Students/2017/HallmanMarcin/builderPattern/src/main/resources/log4j.properties
03Builder/Students/2017/HallmanMarcin/builderPattern/src/test/java/pl/mhallman/java/builderPattern/AppTest.java
03Builder/Students/2017/HallmanMarcin/builderPattern/target/classes/log4j.properties
03Builder/Students/2017/HallmanMarcin/fluentBuilderPattern/fluentBuilderPattern.iml
03Builder/Students/2017/HallmanMarcin/fluentBuilderPattern/pom.xml
03Builder/Students/2017/HallmanMarcin/fluentBuilderPattern/src/main/java/pl/mhallman/java/fluentBuilderPattern/App.java
03Builder/Students/2017/HallmanMarcin/fluentBuilderPattern/src/main/java/pl/mhallman/java/fluentBuilderPattern/model/Appetizer.java
03Builder/Students/2017/HallmanMarcin/fluentBuilderPattern/src/main/java/pl/mhallman/java/fluentBuilderPattern/model/Dessert.java
03Builder/Students/2017/HallmanMarcin/fluentBuilderPattern/src/main/java/pl/mhallman/java/fluentBuilderPattern/model/MainCourse.java
03Builder/Students/2017/HallmanMarcin/fluentBuilderPattern/src/main/java/pl/mhallman/java/fluentBuilderPattern/model/Meal.java
03Builder/Students/2017/HallmanMarcin/fluentBuilderPattern/src/main/resources/log4j.properties
03Builder/Students/2017/HallmanMarcin/fluentBuilderPattern/src/test/java/pl/mhallman/java/fluentBuilderPattern/AppTest.java
03Builder/Students/2017/HallmanMarcin/fluentBuilderPattern/target/classes/log4j.properties

Hi,
This PR contains Builder(Simple and Fluid). Both were rated during 25-26.11 classes.
Thanks,
Marcin Hallman

Design Patterns :: Builder(Simple/Fluid)

---

02Fabryka/Students/2018/artkolinski/02Factory/Factory/AbstractDeviceFactory.cs
02Fabryka/Students/2018/artkolinski/02Factory/Factory/App.config
02Fabryka/Students/2018/artkolinski/02Factory/Factory/Factory.csproj
02Fabryka/Students/2018/artkolinski/02Factory/Factory/Factory.sln
02Fabryka/Students/2018/artkolinski/02Factory/Factory/Models/BookReader.cs
02Fabryka/Students/2018/artkolinski/02Factory/Factory/Models/Device.cs
02Fabryka/Students/2018/artkolinski/02Factory/Factory/Models/Smartphone.cs
02Fabryka/Students/2018/artkolinski/02Factory/Factory/Models/Tablet.cs
02Fabryka/Students/2018/artkolinski/02Factory/Factory/Program.cs
02Fabryka/Students/2018/artkolinski/02Factory/Factory/Properties/AssemblyInfo.cs
02Fabryka/Students/2018/artkolinski/02Factory/Factory/ReflectionDeviceFactory.cs
02Fabryka/Students/2018/artkolinski/02Factory/Factory/SimpleDeviceFactory.cs
02Fabryka/Students/2018/artkolinski/02Factory/FactoryTests/AbstractFactoryTests.cs
02Fabryka/Students/2018/artkolinski/02Factory/FactoryTests/FactoryTests.csproj
02Fabryka/Students/2018/artkolinski/02Factory/FactoryTests/Properties/AssemblyInfo.cs
02Fabryka/Students/2018/artkolinski/02Factory/FactoryTests/ReflectionFactoryTests.cs
02Fabryka/Students/2018/artkolinski/02Factory/FactoryTests/SimpleFactoryTests.cs

added abstract, reflection and simple factory with tests

---

01Singleton/Students/2018/WieckoDawid/Singleton/Singleton/DefaultSingleton.cs
01Singleton/Students/2018/WieckoDawid/Singleton/Singleton/DoubleCheckLockingSingleton.cs
01Singleton/Students/2018/WieckoDawid/Singleton/Singleton/Program.cs
01Singleton/Students/2018/WieckoDawid/Singleton/Singleton/SingleCheckSingleton.cs
01Singleton/Students/2018/WieckoDawid/Singleton/Singleton/Singleton.csproj
01Singleton/Students/2018/WieckoDawid/Singleton/Singleton/Singleton.sln
01Singleton/Students/2018/WieckoDawid/Singleton/Singleton/SingletonA.cs
01Singleton/Students/2018/WieckoDawid/Singleton/Singleton/SingletonB.cs
01Singleton/Students/2018/WieckoDawid/Singleton/Singleton/SingletonC.cs
01Singleton/Students/2018/WieckoDawid/Singleton/SingletonThreadSafetyTests/DefaultSingletonTests.cs
01Singleton/Students/2018/WieckoDawid/Singleton/SingletonThreadSafetyTests/InheritanceTests.cs
01Singleton/Students/2018/WieckoDawid/Singleton/SingletonThreadSafetyTests/SingletonThreadSafetyTests.csproj

Add singleton - Inheritance & Thread Safety

Add singleton

---

Zadania/2018_Marek_Przybolewski/ConsoleApp1.sln
Zadania/2018_Marek_Przybolewski/ConsoleApp1/App.config
Zadania/2018_Marek_Przybolewski/ConsoleApp1/Character.cs
Zadania/2018_Marek_Przybolewski/ConsoleApp1/CharactersManager.cs
Zadania/2018_Marek_Przybolewski/ConsoleApp1/ConsoleApp1.csproj
Zadania/2018_Marek_Przybolewski/ConsoleApp1/Game.cs
Zadania/2018_Marek_Przybolewski/ConsoleApp1/GameObserver.cs
Zadania/2018_Marek_Przybolewski/ConsoleApp1/Grass.cs
Zadania/2018_Marek_Przybolewski/ConsoleApp1/Map.cs
Zadania/2018_Marek_Przybolewski/ConsoleApp1/Program.cs
Zadania/2018_Marek_Przybolewski/ConsoleApp1/Properties/AssemblyInfo.cs
Zadania/2018_Marek_Przybolewski/ConsoleApp1/Sheep.cs
Zadania/2018_Marek_Przybolewski/ConsoleApp1/Wolf.cs

Singleton
Observer
State
Prototype

add solution

---

Zadania/2019_Bartosz_Pawlowski/zad2.py

Egzamin 03.03.2019

---

04Prototype/Students/2019/MazepaMariusz/pom.xml
04Prototype/Students/2019/MazepaMariusz/src/main/java/Album.java
04Prototype/Students/2019/MazepaMariusz/src/main/java/AlbumManager.java
04Prototype/Students/2019/MazepaMariusz/src/main/java/AlbumPrototype.java
04Prototype/Students/2019/MazepaMariusz/src/main/java/DisplayManager.java
04Prototype/Students/2019/MazepaMariusz/src/main/java/MusicStore.java
04Prototype/Students/2019/MazepaMariusz/src/main/java/MusicStoreManager.java
04Prototype/Students/2019/MazepaMariusz/src/main/java/MusicStorePrototype.java
04Prototype/Students/2019/MazepaMariusz/src/main/java/Person.java
04Prototype/Students/2019/MazepaMariusz/src/main/java/Song.java
04Prototype/Students/2019/MazepaMariusz/src/main/java/SongManager.java
04Prototype/Students/2019/MazepaMariusz/src/main/java/SongPrototype.java
04Prototype/Students/2019/MazepaMariusz/src/test/java/MusicTest.java

**Język programowania:** Java
**Zagłębienie referencyjne:** 3

Prototyp - zagłębienie referencyjne 3.

---

ProjektyStudentow/2019_Novik_Aliaksandr/.gitignore
ProjektyStudentow/2019_Novik_Aliaksandr/pom.xml
ProjektyStudentow/2019_Novik_Aliaksandr/src/main/java/ug/anovik/dp/Camera.java
ProjektyStudentow/2019_Novik_Aliaksandr/src/main/java/ug/anovik/dp/Manager.java
ProjektyStudentow/2019_Novik_Aliaksandr/src/main/java/ug/anovik/dp/Memory.java
ProjektyStudentow/2019_Novik_Aliaksandr/src/main/java/ug/anovik/dp/MobileDevice.java
ProjektyStudentow/2019_Novik_Aliaksandr/src/main/java/ug/anovik/dp/MobileDeviceAbstractFactory.java
ProjektyStudentow/2019_Novik_Aliaksandr/src/main/java/ug/anovik/dp/MobileDeviceFactory.java
ProjektyStudentow/2019_Novik_Aliaksandr/src/main/java/ug/anovik/dp/Phone.java
ProjektyStudentow/2019_Novik_Aliaksandr/src/main/java/ug/anovik/dp/PhoneFactory.java
ProjektyStudentow/2019_Novik_Aliaksandr/src/main/java/ug/anovik/dp/PhotoType.java
ProjektyStudentow/2019_Novik_Aliaksandr/src/main/java/ug/anovik/dp/Tablet.java
ProjektyStudentow/2019_Novik_Aliaksandr/src/main/java/ug/anovik/dp/TabletFactory.java
ProjektyStudentow/2019_Novik_Aliaksandr/src/main/java/ug/anovik/dp/adapter/Antutu.java
ProjektyStudentow/2019_Novik_Aliaksandr/src/main/java/ug/anovik/dp/adapter/Geekbench.java
ProjektyStudentow/2019_Novik_Aliaksandr/src/main/java/ug/anovik/dp/adapter/Ranking.java
ProjektyStudentow/2019_Novik_Aliaksandr/src/main/java/ug/anovik/dp/adapter/Rankingable.java
ProjektyStudentow/2019_Novik_Aliaksandr/src/main/java/ug/anovik/dp/builder/Address.java
ProjektyStudentow/2019_Novik_Aliaksandr/src/main/java/ug/anovik/dp/builder/Company.java
ProjektyStudentow/2019_Novik_Aliaksandr/src/main/java/ug/anovik/dp/builder/Order.java
ProjektyStudentow/2019_Novik_Aliaksandr/src/main/java/ug/anovik/dp/builder/OrderBuilder.java
ProjektyStudentow/2019_Novik_Aliaksandr/src/main/java/ug/anovik/dp/facade/MobileDeviceFacade.java
ProjektyStudentow/2019_Novik_Aliaksandr/src/main/java/ug/anovik/dp/observer/NewPhoneObserver.java
ProjektyStudentow/2019_Novik_Aliaksandr/src/main/java/ug/anovik/dp/observer/NewPhonesTopic.java
ProjektyStudentow/2019_Novik_Aliaksandr/src/main/java/ug/anovik/dp/observer/Observer.java
ProjektyStudentow/2019_Novik_Aliaksandr/src/main/java/ug/anovik/dp/observer/Subject.java
ProjektyStudentow/2019_Novik_Aliaksandr/src/test/java/ug/anovik/dp/test/ProjectTest.java

A. Novik - project
